---
- name: "Install pmg role dependencies"
  become: yes
  apt: 
    name: 
      - "software-properties-common"
      - "apt-transport-https"
      - "haveged"
    state: latest
    update_cache: yes
  tags: ["pmg"]

- name: "Add contrib repository"
  replace:
    dest: /etc/apt/sources.list
    regexp: '^(deb.+)(?<! non-free)$'
    replace: '\1 non-free'
  tags: ["pmg"]

# Run pmg package configuration and setup
- import_tasks: setup.yml

- name: "Deploy Proxmox NAG patch for no-subscription packages"
  become: yes
  block:
  - name: "Deploy /usr/share/pmg_nag_script.sh"
    become: true
    template:
      src: "pmg_nag_script.sh.j2"
      dest: "/usr/share/pmg_nag_script.sh"
      mode: a+x

  - name: "Run /usr/share/pmg_nag_script.sh"
    become: true
    command: 'bash /usr/share/pmg_nag_script.sh'

  - name: "Deploy apt hook /etc/apt/apt.conf.d/86pmg-nags"
    become: true
    template:
      src: "86pmg-nags.j2"
      dest: "/etc/apt/apt.conf.d/86pmg-nags"
      mode: a+x
  when: pmg_package_source|lower is search('(nosubscription|custom)')
  tags: ["pmg","pmg_remove_nag"]

- name: "Remove /etc/apt/apt.conf.d/86pmg-nags"
  become: true
  file:
    path: "/etc/apt/apt.conf.d/86pmg-nags"
    state: absent
  when: pmg_package_source|lower is search('(enterprise)')
  tags: ["pmg","pmg_remove_nag"]

- name: "Deploy bind9 configuration"
  become: true
  template: src={{ item.src }}.j2 dest={{ item.dest }} mode={{ item.mode | default(omit) }}
  with_items:
    - src: named_conf_options
      dest: /etc/bind/named.conf.options
    - src: bind9
      dest: /etc/default/bind9
    - src: resolv_conf
      dest: /etc/resolv.conf
  notify:
    - disable systemd-resolved
    - restart bind9
    - restart postfix
  tags: ["pmg"]

